version: 2

sources:
  - name: home_metrics_raw
    schema: public
    description: "Raw data tables for Home Metrics project"

    tables:
      - name: raw_media_activity
        description: "Raw table containing media activity data (Prowlarr, Sonarr, Radarr)"
        columns:
          - name: id
            description: "Unique identifier for each media activity record"
          - name: source
            description: "Source of the media activity (e.g., Prowlarr, Sonarr, Radarr)"
          - name: user_name
            description: "Username"
          - name: media_type
            description: "Type of media activity (e.g., download, delete)"
          - name: title
            description: "Title of the media item"
          - name: series_title
            description: "Title of the series (if applicable)"
          - name: duration
            description: "Duration of the media activity in seconds"
          - name: watched_at
            description: "Timestamp when the media was watched"
          - name: inserted_at
            description: "Timestamp when the record was inserted into the raw table"
          - name: metadata
            description: "Additional metadata related to the media activity in JSON format"

      - name: raw_media_library
        description: "Raw table containing media library"
        columns:
          - name: id
            description: "Unique identifier for each media library record"
          - name: source
            description: "Source of the media library (e.g., Sonarr, Radarr)"
          - name: media_type
            description: "Type of media (e.g., movie, tv show)"
          - name: library_name
            description: "Name of the library"
          - name: item_count
            description: "Number of items in the library"
          - name: total_size_bytes
            description: "Total size of the library in bytes"
          - name: recorded_at
            description: "Timestamp when the library record was recorded"
          - name: inserted_at
            description: "Timestamp when the record was inserted into the raw table"
          - name: metadata
            description: "Additional metadata related to the media library in JSON format"

      - name: raw_pihole_metrics
        description: "Raw table containing Pi-Hole metrics data"
        columns:
          - name: id
            description: "Unique identifier for each Pi-Hole metrics record"
          - name: pihole_instance
            description: "Identifier for the Pi-Hole instance"
          - name: total_queries
            description: "Total number of DNS queries processed"
          - name: blocked_queries
            description: "Number of DNS queries that were blocked"
          - name: percent_blocked
            description: "Percentage of DNS queries that were blocked"
          - name: unique_domains
            description: "Number of unique domains queried"
          - name: unique_clients
            description: "Number of unique clients making DNS queries"
          - name: recorded_at
            description: "Timestamp when the metrics were recorded"
          - name: inserted_at
            description: "Timestamp when the record was inserted into the raw table"
          - name: top_blocked_domains
            description: "Top blocked domains in JSON format"
          - name: top_queries
            description: "Top queried domains in JSON format"

      - name: raw_power_consumption
        description: "Raw table containing power consumption data for House"
        loaded_at_field: recorded_at
        freshness:
          warn_after: {count: 30, period: minute}
          error_after: {count: 1, period: hour}
        columns:
          - name: id
            description: "Unique identifier for each power consumption record"
          - name: entity_id
            description: "Identifier for the power consumption entity"
          - name: friendly_name
            description: "Friendly name of the power consumption entity"
          - name: state
            description: "Power consumption state value"
          - name: unit_of_measurement
            description: "Unit of measurement for the power consumption state"
          - name: device_class
            description: "Device class of the power consumption entity"
          - name: recorded_at
            description: "Timestamp when the power consumption was recorded"
          - name: inserted_at
            description: "Timestamp when the record was inserted into the raw table"
          - name: attributes
            description: "Additional attributes related to the power consumption entity in JSON format"

      - name: raw_system_health
        description: "Raw table containing system health metrics"
        columns:
          - name: id
            description: "Unique identifier for each system health record"
          - name: hostname
            description: "Hostname of the system"
          - name: cpu_percent
            description: "CPU usage percentage"
          - name: memory_percent
            description: "Memory usage percentage"
          - name: disk_percent
            description: "Disk usage percentage"
          - name: temperature_c
            description: "System temperature in Celsius"
          - name: recorded_at
            description: "Timestamp when the system health metrics were recorded"
          - name: inserted_at
            description: "Timestamp when the record was inserted into the raw table"
          - name: metadata
            description: "Additional metadata related to the system health in JSON format"

      - name: raw_n8n_alerts
        description: "Unified alerts table for workflow failures and data staleness alerts"
        columns:
          - name: id
            description: "Unique identifier for each alert record"
          - name: alert_type
            description: "Type of alert (workflow_failure, stale_data, no_data, threshold_breach)"
          - name: severity
            description: "Severity level (info, warning, error, critical)"
          - name: source
            description: "Source of the alert (workflow name or table name)"
          - name: title
            description: "Short alert title"
          - name: message
            description: "Detailed alert message"
          - name: triggered_at
            description: "Timestamp when the alert was triggered"
          - name: resolved_at
            description: "Timestamp when the alert was resolved (NULL if still active)"
          - name: inserted_at
            description: "Timestamp when the record was inserted"
          - name: metadata
            description: "Additional metadata in JSON format (execution_id, error_stack, etc.)"

      - name: raw_n8n_workflow_runs
        description: "Raw table tracking n8n workflow executions"
        columns:
          - name: id
            description: "Unique identifier for each workflow run"
          - name: workflow_id
            description: "ID of the workflow"
          - name: workflow_name
            description: "Name of the workflow"
          - name: source
            description: "Source/trigger of the workflow run"
          - name: status
            description: "Execution status (success, error, etc.)"
          - name: started_at
            description: "Timestamp when the workflow started"
          - name: finished_at
            description: "Timestamp when the workflow finished"
          - name: inserted_at
            description: "Timestamp when the record was inserted"
          - name: metadata
            description: "Additional metadata in JSON format"
